const EventList = [
  {
    index: 1,
    image: "/images/beach.png",
    title: "Hello, how do you do?",
    coordinator: "Seamoon Pandey",
    subcoordinator: "Rakshya Raut",
    startDate: "2024-02-05",
    endDate: "2024-02-07",
    venue: "WRC",
    time: "10 am onwards",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    buttonText: "Learn More",
    link: "/event/1",
  },
  {
    index: 2,
    image: "/images/OIP.jpeg",
    title: "Datathon",
    coordinator: "Seamoon Pandey",
    subcoordinator: "Rakshya Raut",
    startDate: "2024-02-05",
    endDate: "2024-02-07",
    venue: "WRC",
    time: "10 am onwards",
    description:
      "Lorem ipsum sorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    buttonText: "Learn More",
    link: "/event/2",
  },
  {
    index: 3,
    image: "/images/beach.png",
    title: "Code With Coffee",
    coordinator: "Seamoon Pandey",
    subcoordinator: "Rakshya Raut",
    startDate: "2024-02-05",
    endDate: "2024-02-07",
    venue: "WRC",
    time: "10 am onwards",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    buttonText: "Learn More",
    link: "/event/3",
  },
  {
    index: 4,
    image: "/images/OIP.jpeg",
    title: "Capture The Flag",
    coordinator: "Seamoon Pandey",
    subcoordinator: "Rakshya Raut",
    startDate: "2024-02-05",
    endDate: "2024-02-07",
    venue: "WRC",
    time: "10 am onwards",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    buttonText: "Learn More",
    link: "/event/4",
  },
  {
    index: 5,
    image: "/images/beach.png",
    title: "Design Workshop",
    coordinator: "Seamoon Pandey",
    subcoordinator: "Rakshya Raut",
    startDate: "2024-02-05",
    endDate: "2024-02-07",
    venue: "WRC",
    time: "10 am onwards",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    buttonText: "Learn More",
    link: "/event/5",
  },
  {
    index: 6,
    image: "/images/OIP.jpeg",
    title: "Hello World",
    coordinator: "Seamoon Pandey",
    subcoordinator: "Rakshya Raut",
    startDate: "2024-02-05",
    endDate: "2024-02-07",
    venue: "WRC",
    time: "10 am onwards",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
    buttonText: "Learn More",
    link: "/event/6",
  },
  {
    index: 7,
    image: "/images/beach.png",
    title: "Bootcamp",
    coordinator: "Seamoon Pandey",
    subcoordinator: "Rakshya Raut",
    startDate: "2024-02-05",
    endDate: "2024-02-07",
    venue: "WRC",
    time: "10 am onwards",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    buttonText: "Learn More",
    link: "/event/7",
  },
  {
    index: 8,
    image: "/images/beach.png",
    title: "Woodcamp",
    coordinator: "Seamoon Pandey",
    subcoordinator: "Rakshya Raut",
    startDate: "2024-02-05",
    endDate: "2024-02-07",
    venue: "WRC",
    time: "10 am onwards",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    buttonText: "Learn More",
    link: "/event/8",
  },
];

export default EventList;
